version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  app:
    container_name: app
    build: .
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - redis

  celery_worker:
    container_name: celery_worker
    build: .
    command: poetry run celery -A celery_worker worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: always

  celery_beat:
    container_name: celery_beat
    build: .
    command: poetry run celery -A celery_worker beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: always

  flower:
    container_name: flower
    build: .
    command: poetry run celery -A celery_worker flower --port=5555
    ports:
      - "5556:5555"
    depends_on:
      - redis
      - celery_worker
    restart: always
